dist: trusty
sudo: false

language: node_js
node_js:
  - '12'

env:
  global:
    - CC_TEST_REPORTER_ID=e6493f43e4d6ae0ee475e1d1fc984dd3a04056440c53c6ced46a50434c3b29e7

cache:
  directories:
    - ./node_modules

install:
  - npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run test:ci

after_script:
  - mkdir coverage
  - mv tests/coverage/lcov.info coverage/lcov.info
  - ./cc-test-reporter after-build -t lcov --exit-code $TRAVIS_TEST_RESULT
  - npx coveralls <./coverage/lcov.info
